package com.harana.sdk.shared.models.flow.catalog

import com.harana.sdk.shared.models.flow.actiontypes._
import com.harana.sdk.shared.models.flow.actiontypes.custom._
import com.harana.sdk.shared.models.flow.actiontypes.read._
import com.harana.sdk.shared.models.flow.actiontypes.spark.wrappers.estimators._
import com.harana.sdk.shared.models.flow.actiontypes.spark.wrappers.evaluators._
import com.harana.sdk.shared.models.flow.actiontypes.spark.wrappers.transformers._
import com.harana.sdk.shared.models.flow.actiontypes.write._

import scala.scalajs.reflect.annotation.EnableReflectiveInstantiation

@EnableReflectiveInstantiation
class ReadDatasource extends ActionType with ReadDatasourceInfo

@EnableReflectiveInstantiation
class ReadTransformer extends ActionType with ReadTransformerInfo

@EnableReflectiveInstantiation
class WriteDatasource extends ActionType with WriteDatasourceInfo

@EnableReflectiveInstantiation
class WriteTransformer extends ActionType with WriteTransformerInfo

@EnableReflectiveInstantiation
class Source extends ActionType with SourceInfo

@EnableReflectiveInstantiation
class Sink extends ActionType with SinkInfo

@EnableReflectiveInstantiation
class Evaluate extends ActionType with EvaluateInfo

@EnableReflectiveInstantiation
class Fit extends ActionType with FitInfo

@EnableReflectiveInstantiation
class FitPlusTransform extends ActionType with FitPlusTransformInfo

@EnableReflectiveInstantiation
class Transform extends ActionType with TransformInfo

@EnableReflectiveInstantiation
class Join extends ActionType with JoinInfo

@EnableReflectiveInstantiation
class Split extends ActionType with SplitInfo

@EnableReflectiveInstantiation
class Union extends ActionType with UnionInfo

@EnableReflectiveInstantiation
class SqlCombine extends ActionType with SqlCombineInfo

@EnableReflectiveInstantiation
class SortTransformation extends ActionType with SortTransformationInfo

@EnableReflectiveInstantiation
class FilterColumns extends ActionType with FilterColumnsInfo

@EnableReflectiveInstantiation
class FilterRows extends ActionType with FilterRowsInfo

@EnableReflectiveInstantiation
class HandleMissingValues extends ActionType with HandleMissingValuesInfo

@EnableReflectiveInstantiation
class Projection extends ActionType with ProjectionInfo

@EnableReflectiveInstantiation
class CreateCustomTransformer extends ActionType with CreateCustomTransformerInfo

@EnableReflectiveInstantiation
class SqlColumnTransformation extends ActionType with SqlColumnTransformationInfo

@EnableReflectiveInstantiation
class SqlTransformation extends ActionType with SqlTransformationInfo

@EnableReflectiveInstantiation
class PythonColumnTransformation extends ActionType with PythonColumnTransformationInfo

@EnableReflectiveInstantiation
class PythonTransformation extends ActionType with PythonTransformationInfo

@EnableReflectiveInstantiation
class RColumnTransformation extends ActionType with RColumnTransformationInfo

@EnableReflectiveInstantiation
class RTransformation extends ActionType with RTransformationInfo

@EnableReflectiveInstantiation
class AssembleVector extends ActionType with AssembleVectorInfo

@EnableReflectiveInstantiation
class Binarize extends ActionType with BinarizeInfo

@EnableReflectiveInstantiation
class ComposeDatetime extends ActionType with ComposeDatetimeInfo

@EnableReflectiveInstantiation
class ConvertType extends ActionType with ConvertTypeInfo

@EnableReflectiveInstantiation
class DCT extends ActionType with DCTInfo

@EnableReflectiveInstantiation
class DecomposeDatetime extends ActionType with DecomposeDatetimeInfo

@EnableReflectiveInstantiation
class GetFromVector extends ActionType with GetFromVectorInfo

@EnableReflectiveInstantiation
class Normalize extends ActionType with NormalizeInfo

@EnableReflectiveInstantiation
class PolynomialExpand extends ActionType with PolynomialExpandInfo

@EnableReflectiveInstantiation
class QuantileDiscretizer extends ActionType with QuantileDiscretizerInfo

@EnableReflectiveInstantiation
class StringIndexer extends ActionType with StringIndexerInfo

@EnableReflectiveInstantiation
class VectorIndexer extends ActionType with VectorIndexerInfo

@EnableReflectiveInstantiation
class MinMaxScaler extends ActionType with MinMaxScalerInfo

@EnableReflectiveInstantiation
class StandardScaler extends ActionType with StandardScalerInfo

@EnableReflectiveInstantiation
class ConvertToNGrams extends ActionType with ConvertToNGramsInfo

@EnableReflectiveInstantiation
class CountVectorizer extends ActionType with CountVectorizerInfo

@EnableReflectiveInstantiation
class HashingTF extends ActionType with HashingTFInfo

@EnableReflectiveInstantiation
class IDF extends ActionType with IDFInfo

@EnableReflectiveInstantiation
class RemoveStopWords extends ActionType with RemoveStopWordsInfo

@EnableReflectiveInstantiation
class Tokenize extends ActionType with TokenizeInfo

@EnableReflectiveInstantiation
class TokenizeWithRegex extends ActionType with TokenizeWithRegexInfo

@EnableReflectiveInstantiation
class Word2Vec extends ActionType with Word2VecInfo

@EnableReflectiveInstantiation
class GridSearch extends ActionType with GridSearchInfo

@EnableReflectiveInstantiation
class CreateAFTSurvivalRegression extends ActionType with CreateAFTSurvivalRegressionInfo

@EnableReflectiveInstantiation
class CreateDecisionTreeRegression extends ActionType with CreateDecisionTreeRegressionInfo

@EnableReflectiveInstantiation
class CreateGBTRegression extends ActionType with CreateGBTRegressionInfo

@EnableReflectiveInstantiation
class CreateIsotonicRegression extends ActionType with CreateIsotonicRegressionInfo

@EnableReflectiveInstantiation
class CreateLinearRegression extends ActionType with CreateLinearRegressionInfo

@EnableReflectiveInstantiation
class CreateRandomForestRegression extends ActionType with CreateRandomForestRegressionInfo

@EnableReflectiveInstantiation
class CreateDecisionTreeClassifier extends ActionType with CreateDecisionTreeClassifierInfo

@EnableReflectiveInstantiation
class CreateGBTClassifier extends ActionType with CreateGBTClassifierInfo

@EnableReflectiveInstantiation
class CreateLogisticRegression extends ActionType with CreateLogisticRegressionInfo

@EnableReflectiveInstantiation
class CreateMultilayerPerceptronClassifier extends ActionType with CreateMultilayerPerceptronClassifierInfo

@EnableReflectiveInstantiation
class CreateNaiveBayes extends ActionType with CreateNaiveBayesInfo

@EnableReflectiveInstantiation
class CreateRandomForestClassifier extends ActionType with CreateRandomForestClassifierInfo

@EnableReflectiveInstantiation
class CreateKMeans extends ActionType with CreateKMeansInfo

@EnableReflectiveInstantiation
class CreateLDA extends ActionType with CreateLDAInfo

@EnableReflectiveInstantiation
class UnivariateFeatureSelector extends ActionType with UnivariateFeatureSelectorInfo

@EnableReflectiveInstantiation
class CreateALS extends ActionType with CreateALSInfo

@EnableReflectiveInstantiation
class PCA extends ActionType with PCAInfo

@EnableReflectiveInstantiation
class CreatePythonEvaluator extends ActionType with CreatePythonEvaluatorInfo

@EnableReflectiveInstantiation
class CreateREvaluator extends ActionType with CreateREvaluatorInfo

@EnableReflectiveInstantiation
class CreateBinaryClassificationEvaluator extends ActionType with CreateBinaryClassificationEvaluatorInfo

@EnableReflectiveInstantiation
class CreateMulticlassClassificationEvaluator extends ActionType with CreateMulticlassClassificationEvaluatorInfo

@EnableReflectiveInstantiation
class CreateRegressionEvaluator extends ActionType with CreateRegressionEvaluatorInfo