package com.harana.modules.shopify.models

import java.time.Instant

case class Order(id: Long,
                 email: String,
                 closedAt: Option[Instant],
                 createdAt: Instant,
                 updatedAt: Instant,
                 number: Int,
                 note: Option[String],
                 token: String,
                 totalPrice: BigDecimal,
                 subtotalPrice: BigDecimal,
                 totalWeight: Long,
                 totalTax: BigDecimal,
                 taxesIncluded: Boolean = false,
                 currency: Option[String],
                 financialStatus: String,
                 totalDiscounts: BigDecimal,
                 totalLineItemsPrice: BigDecimal,
                 cartToken: String,
                 buyerAcceptsMarketing: Boolean = false,
                 name: String,
                 referringSite: String,
                 landingSite: String,
                 cancelledAt: Option[Instant],
                 cancelReason: Option[String],
                 userId: Option[Long],
                 locationId: Option[Long],
                 processedAt: Instant,
                 browserIp: String,
                 orderNumber: Long,
                 processingMethod: String,
                 sourceName: String,
                 fulfillmentStatus: Option[String],
                 tags: String,
                 orderStatusUrl: String,
                 lineItems: List[LineItem],
                 fulfillments: List[Fulfilment],
                 billingAddress: Address,
                 shippingAddress: Option[Address],
                 customer: Customer,
                 shippingLines: List[ShippingLine],
                 taxLines: List[TaxLine],
                 noteAttributes: List[Attribute],
                 refunds: List[Refund])