---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
  name: argo-rollouts
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argo-rollouts
    spec:
      containers:
        - command:
            - /bin/rollouts-controller
          image: argoproj/argo-rollouts:v0.7.2
          imagePullPolicy: Always
          name: argo-rollouts
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      serviceAccountName: argo-rollouts
      volumes:
        - emptyDir: {}
          name: tmp