name: Scala Steward

# This workflow will launch at 00:00 every Sunday
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.SCALA_STEWARD_TOKEN }}
          author-email: 657041+nadenf@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}