apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-home
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/harana"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: user-home
  namespace: harana-designer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual